server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

database:
  default:
    type:  "mysql"
    link:  "goframe:CE335yBMB28rCD4P@tcp(152.136.193.22:3306)/goframe"

logger:
  level : "all"
  stdout: true



