// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-demo/internal/service/internal/dao/internal"
)

// blogDao is the data access object for table blog.
// You can define custom methods on it to extend its functionality as you wish.
type blogDao struct {
	*internal.BlogDao
}

var (
	// Blog is globally public accessible object for table blog operations.
	Blog = blogDao{
		internal.NewBlogDao(),
	}
)

// Fill with you ideas below.
