// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Blog is the golang structure of table blog for DAO operations like Where/Data.
type Blog struct {
	g.Meta `orm:"table:blog, do:true"`
	Id     interface{} //
	Title  interface{} //
	Author interface{} //
	Desc   interface{} //
}
