// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Blog is the golang structure for table blog.
type Blog struct {
	Id     uint   `json:"id"     ` //
	Title  string `json:"title"  ` //
	Author uint   `json:"author" ` //
	Desc   string `json:"desc"   ` //
}
